### ISSUE TITLE
Перенеси скрипты с head

### ISSUE THREAD

**Issue by yuchiko** [YuriiHoliuk/JWoodLanding#1]
Очень редко когда действительно нужно, чтобы скрипты были в `<head> `
Советую перенести перед закрывающим тегом `</body>` чтобы не блокировалась загрузка страницы 

В твоем случае я про эти
```
<script src="js/libs.min.js"></script>
<script src="main.js"></script>
```

**Comment by YuriiHoliuk** [comment]
Переніс, загрузка сторінки суттєво зменшилась. Дякую!
