### ISSUE TITLE
Используй всю силу вложения с помощью SASS

### ISSUE THREAD

**Issue by yuchiko** [YuriiHoliuk/JWoodLanding#2]
По всем твоим файлам стилей прослеживается такая запись:
```
.about-me {
  display: flex;
  align-items: center;
  @include tablet {
    display: block;
  }
}

.about-me__layout-left {
  flex: 1 1;
  order: -1;
  @include laptop {
    flex: 4 1;
  }
}
```

Ты используешь БЭМ, а для него уже есть некоторые правила, которые могут тебе упростить жизнь. Не нужно повторять название блока для всех его элементов. Можно использовать короткую запись `&`

Нужно немного переписать код, чтобы `&` знал, что возвращать

```
.about-me {
  display: flex;
  align-items: center;
  @include tablet {
    display: block;
  }

  &__layout-left {
    flex: 1 1;
    order: -1;
    @include laptop {
      flex: 4 1;
    }
  }

}
```

Подробнее можешь почитать тут:
[easier-bem-ing-with-sass](http://alwaystwisted.com/articles/2014-02-27-even-easier-bem-ing-with-sass-33)

**Comment by yuchiko** [comment]
еще статья с [bem-mixins](https://css-tricks.com/snippets/sass/bem-mixins/)

**Comment by YuriiHoliuk** [comment]
Виправив
